source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'DanceSpirit' do
    pod 'Alamofire', '~> 4.5'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Moya'
    pod 'ObjectMapper', '~> 2.2'
end
